apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-config
  namespace: saas-foundation
  labels:
    app.kubernetes.io/name: saas-foundation
    app.kubernetes.io/part-of: saas-foundation
data:
  NODE_ENV: production
  NEXTAUTH_URL: https://example.com
  BFF_INTERNAL_URL: http://saas-bff-service:3001
  MENU_LAYOUT: left
  THEME: light
  PORT: "3001"
  WEB_APP_URL: https://example.com
