apiVersion: v1
kind: Secret
metadata:
  name: saas-secrets
  namespace: saas-foundation
  labels:
    app.kubernetes.io/name: saas-foundation
    app.kubernetes.io/part-of: saas-foundation
type: Opaque
stringData:
  NEXTAUTH_SECRET: REPLACE_ME_WITH_STRONG_NEXTAUTH_SECRET
  DATABASE_URL: postgresql://REPLACE_ME_POSTGRES_USER:REPLACE_ME_POSTGRES_PASSWORD@saas-postgres-service:5432/REPLACE_ME_POSTGRES_DB
  POSTGRES_USER: REPLACE_ME_POSTGRES_USER
  POSTGRES_PASSWORD: REPLACE_ME_POSTGRES_PASSWORD
  POSTGRES_DB: REPLACE_ME_POSTGRES_DB
  GOOGLE_CLIENT_ID: REPLACE_ME_WITH_GOOGLE_CLIENT_ID_OR_DUMMY
  GOOGLE_CLIENT_SECRET: REPLACE_ME_WITH_GOOGLE_CLIENT_SECRET_OR_DUMMY
  GITHUB_ID: REPLACE_ME_WITH_GITHUB_CLIENT_ID_OR_DUMMY
  GITHUB_SECRET: REPLACE_ME_WITH_GITHUB_CLIENT_SECRET_OR_DUMMY
  GMAIL_USER: REPLACE_ME_WITH_GMAIL_USER_OR_EMPTY
  GMAIL_APP_PASSWORD: REPLACE_ME_WITH_GMAIL_APP_PASSWORD_OR_EMPTY
